export default function Features() {
  return (
    <section className="w-full bg-black -mt-1 px-4"> {/* <- HILANGKAN GAP! */}
      {/* GRID CONTAINER */}
      <div className="max-w-[1400px] mx-auto grid grid-cols-12 gap-6 pt-20"> {/* pindahin jarak ke dalam */}

        {/* LEFT — AI ROADMAP */}
        <div className="col-span-8 h-[500px] bg-[#0D0D0D] rounded-2xl relative overflow-hidden p-10">
          <div className="bg-[rgba(255,107,0,0.10)] rounded-full w-[120px] h-[32px] flex items-center justify-center px-3">
            <span className="text-[#FF6B00] text-[12px] tracking-widest font-medium">
              INTELLIGENT
            </span>
          </div>

          <h2 className="text-white text-[40px] font-bold mt-4 leading-tight">
            AI Roadmap
          </h2>

          <p className="text-[#888888] text-[16px] leading-[24px] mt-4 max-w-[420px]">
            Personalized learning paths generated by advanced AI.
            Your career trajectory, mapped to perfection.
          </p>

          {/* ORANGE LINE GRAPH */}
          <div className="absolute bottom-10 right-10 opacity-30">
            <svg width="420" height="160" viewBox="0 0 420 160" fill="none">
              <path
                d="M10 140 C60 120 120 80 180 90 C240 100 300 50 370 30"
                stroke="#FF6B00"
                strokeWidth="4"
                strokeLinecap="round"
              />
              <circle cx="120" cy="95" r="5" fill="#FF6B00" />
              <circle cx="180" cy="90" r="5" fill="#FF6B00" />
              <circle cx="240" cy="100" r="5" fill="#FF6B00" />
              <circle cx="370" cy="30" r="8" fill="#FF6B00" opacity="0.3" />
            </svg>
          </div>
        </div>

        {/* RIGHT — FACE PROCTORING */}
        <div className="col-span-4 h-[500px] bg-[#0D0D0D] rounded-2xl border border-white/5 relative overflow-hidden p-10">
          <div className="bg-[rgba(255,107,0,0.10)] rounded-full w-[80px] h-[32px] flex items-center justify-center px-3">
            <span className="text-[#FF6B00] text-[12px] tracking-widest font-medium">
              SECURE
            </span>
          </div>

          <h2 className="text-white text-[28px] font-bold mt-4 leading-tight">
            Face Proctoring
          </h2>

          <p className="text-[#888888] text-[14px] leading-[20px] mt-4">
            Biometric verification ensures exam integrity.
          </p>

          <div className="absolute bottom-10 right-10 opacity-30">
            <svg width="160" height="160" viewBox="0 0 160 160" fill="none">
              <rect x="20" y="20" width="40" height="40" stroke="#FF6B00" strokeWidth="4" fill="none" />
              <rect x="100" y="20" width="40" height="40" stroke="#FF6B00" strokeWidth="4" fill="none" />
              <rect x="20" y="100" width="40" height="40" stroke="#FF6B00" strokeWidth="4" fill="none" />
              <rect x="100" y="100" width="40" height="40" stroke="#FF6B00" strokeWidth="4" fill="none" />
              <path d="M60 85 Q80 105 100 85" stroke="#FF6B00" strokeWidth="4" fill="none" strokeLinecap="round" />
            </svg>
          </div>
        </div>

        {/* BOTTOM LEFT — 98% */}
        <div className="col-span-6 h-[240px] rounded-2xl bg-gradient-to-r from-[#FF6B00] to-[#FF8533] flex items-center justify-center">
          <div className="text-center">
            <span className="text-black text-[80px] font-bold leading-none">98%</span>
            <p className="text-black/80 text-[16px] mt-2">Placement Rate</p>
          </div>
        </div>

        {/* BOTTOM RIGHT — 3X */}
        <div className="col-span-6 h-[240px] rounded-2xl bg-[#0D0D0D] flex flex-col justify-center px-10">
          <div className="flex items-end gap-3">
            <svg width="36" height="36" viewBox="0 0 36 36" fill="none">
              <path d="M6 24 L18 12 L28 18" stroke="#FF6B00" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            <span className="text-white text-[48px] font-bold leading-none">3x</span>
          </div>
          <p className="text-[#888888] text-[14px] mt-3 max-w-[280px]">
            Faster career progression vs traditional learning
          </p>
        </div>

      </div>
    </section>
  );
}